# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         IO-Unread
version:      0.03
version_from: Unread.pm
installdirs:  site
requires:
    Inline:                        0.44
    Inline::C:                     0.44
    PerlIO:                        1.00
    Test::More:                    0.46

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
